### ISSUE TITLE
Findspark IndexError on Windows 10

### ISSUE THREAD

**Issue by jaypeedevlin** [minrk/findspark#14]
Hi,

I've previously used findspark on Mac OS, but am setting up a Windows system so I can write an instructional guide.

I'm getting the following error, and I'm not sure where to start with troubleshooting:

```
In [2]: findspark.init()
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-2-a4bc4c9af84d> in <module>()
----> 1 findspark.init()

C:\Users\josh\Anaconda3\lib\site-packages\findspark.py in init(spark_home, python_path, edit_rc, edit_profile)
    132     # add pyspark to sys.path
    133     spark_python = os.path.join(spark_home, 'python')
--> 134     py4j = glob(os.path.join(spark_python, 'lib', 'py4j-*.zip'))[0]
    135     sys.path[:0] = [spark_python, py4j]
    136

IndexError: list index out of range
```

Any suggestions on where I might start with this?

**Comment by minrk** [comment]
That suggests py4j isn't where we expect it to be. Can you find py4j and let us know where it is inside spark_home?

**Comment by jaypeedevlin** [comment]
Hey Min, I actually had a lightbulb moment in the middle of the night about what I had done wrong, and your message confirms it - I just made an adjustment to `SPARK_HOME` and it works, the issue was I had appended `/bin/` to the path!

**Comment by gundasuresh** [comment]
Hi Jay, Can you share me path of your solution and where you find that py4j in file structure

**Comment by jaypeedevlin** [comment]
@gundasuresh The problem was that I had used `c:\path\to\spark\directory\bin` instead of `c:\path\to\spark\directory`.  Once I fixed this, it worked as expected.

Where that specific directory is for you depends on where you put spark when you downloaded it.

**Comment by gundasuresh** [comment]
Thanks Jay,
I think you were running spark in Linux operating system right but I am running spark in windows operating system in jupyter notebook with python
I am getting same error in Windows operating system  even after adding bin to my directory path 
any suggestions/help to solve error in windows operating system 
when I try to execute below command in jupyter notebook 
"findspark.init('/path/to/spark/home')"
I am facing below error  
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-8-d0f94835d6a6> in <module>()
----> 1 findspark.init('/path/to/spark/home')

~/anaconda3_420/lib/python3.5/site-packages/findspark.py in init(spark_home, python_path, edit_rc, edit_profile)
    133     # add pyspark to sys.path
    134     spark_python = os.path.join(spark_home, 'python')
--> 135     py4j = glob(os.path.join(spark_python, 'lib', 'py4j-*.zip'))[0]
    136     sys.path[:0] = [spark_python, py4j]
    137 

IndexError: list index out of range
