### ISSUE TITLE
How about a new version on PyPi?

### ISSUE THREAD

**Issue by mgmarino** [minrk/findspark#30]
This is a nice little tool and it looks like quite a lot of work has been done since 1.3.0.  (Indeed some issues have already been addressed.)  I'm happy to install from github, but it would be great to have a 1.4.0. 

Thanks!

**Comment by Hydrugion** [comment]
Yes i want this too, especially the linux `SPARK_HOME` environment.

**Comment by minrk** [comment]
Published 1.4.0
