### ISSUE TITLE
Java gateway process exited before sending its port number in Google Colab with Spark 2.4.5

### ISSUE THREAD

**Issue by 0xDFDFDFDF** [minrk/findspark#32]
Recently, I've encountered `Java gateway process exited before sending its port number` error using findspark in Google Colab. I was puzzled, because the code worked perfectly before. After some investigation, it turned out that it is connected to the latest 1.4.0 version of findspark. I'm using Spark 2.4.5 and OpenJDK 8.

Here's the minimal example to reproduce the error in Google Colab:
```python
!apt-get install openjdk-8-jdk-headless -qq > /dev/null
!wget -q http://www.apache.org/dist/spark/spark-2.4.5/spark-2.4.5-bin-hadoop2.7.tgz
!tar xf spark-2.4.5-bin-hadoop2.7.tgz
!pip install -q findspark pyspark

import os
os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-8-openjdk-amd64"
os.environ["SPARK_HOME"] = "/content/spark-2.4.5-bin-hadoop2.7"

import findspark
import pyspark
from pyspark.sql import SparkSession
from pyspark import SparkContext

findspark.init("spark-2.4.5-bin-hadoop2.7")
sc = pyspark.SparkContext('local[*]')  # Here is the error
spark = SparkSession.builder.appName('abc').getOrCreate()
```
Here's the full stack trace:
```python
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-1-118d2d9079d2> in <module>()
     14 
     15 findspark.init("spark-2.4.5-bin-hadoop2.7")
---> 16 sc = pyspark.SparkContext('local[*]')
     17 spark = SparkSession.builder.appName('abc').getOrCreate()

3 frames
/usr/local/lib/python3.6/dist-packages/pyspark/java_gateway.py in _launch_gateway(conf, insecure)
    106 
    107             if not os.path.isfile(conn_info_file):
--> 108                 raise Exception("Java gateway process exited before sending its port number")
    109 
    110             with open(conn_info_file, "rb") as info:

Exception: Java gateway process exited before sending its port number
```

A temporary workaround for my code is obviously downgrading findspark by doing `!pip install -q findspark==1.3.0 pyspark`, but it does not resolve the problem at its source.

**Comment by snazzer** [comment]
I just ran into this - commenting out https://github.com/minrk/findspark/compare/1.3.0...1.4.0#diff-6259788df2ea7df58e92125f29e9add8R141 fixed it for me. I don't think os.environment should be set to empty string, otherwise it introduces an empty arg to the pyspark invocation.

**Comment by lofoyet** [comment]
Agreed, looking at https://github.com/apache/spark/blob/master/python/pyspark/java_gateway.py#L65
PYSPARK_SUBMIT_ARGS should be not set

**Comment by lofoyet** [comment]
this introduced the change:
https://github.com/minrk/findspark/commit/f9607be604ab95e2bd299691dc75c0ab86b93631#diff-6259788df2ea7df58e92125f29e9add8R133
@caioaao can you help us understand the change?

**Comment by minrk** [comment]
Thanks for tracking it down! Looks like pyspark is mishandling empty vars. 1.4.1 is up and should avoid setting an empty PYSPARK_SUBMIT_ARGS.

**Comment by minrk** [comment]
Thanks for the full repro example! Confirmed 1.4.1 fixes the issue on colab.
