### ISSUE TITLE
Support for finding "pip install pyspark"

### ISSUE THREAD

**Issue by AbdealiJK** [minrk/findspark#34]
I have been using findspark for a while, and it makes life a lot simpler.
But I recently started using the `pip install pyspark` approach in a CI environment.
I found that when I do this, and use `import pyspark` directly, the default behavior of pyspark is to use the system "python3" in the PATH. I'd rather use the venv I am using - as I have my python packages.

### Proposed change

When detecting the spark installation, also detect the `pyspark` installed in the current python installation

### Alternative options

**Option 1**: I could set my `PYTHON_PATH` manually - but I find that using findspark would just be simpler as it would do the standard set of configs I use with my own custom SPARK_HOME.

**Option 2**: I could set my SPARK_HOME=/venv/lib/python3.6/site-packages/pyspark/ - but then It's just a bit more work I need to do - would be better if findspark can auto detect.

**Option 3**: To avoid the python version - I can do the following: `venv/bin/python -c "import os, pyspark; print(os.path.dirname(pyspark.__file__))"`

I am using option 3 as a workaround as of now

### Who would use this feature?

Anyone using the `pip install pyspark` - which I think is just for easier convenience in CI and local installs.

### (Optional): Suggest a solution

I think it's just adding the following:
 - Check if pyspark is installed (Using pkg_resources?)
 - And adding the path to it as a possible SPARK_HOME

**Comment by minrk** [comment]
Interesting. So this is for pyspark that's been pip-installed, but not pip-installed into the current env, right? Can I ask why you haven't done `pip install pyspark` in the env where you want to use it? That should be the easiest way to make everything match, I would think.

**Comment by AbdealiJK** [comment]
@minrk It is in the env I want to use it. But the issue is the pyspark doensn't use my current env by default - it seems to be using the system python for PYSPARK_PYTHON (i.e. on the container side)

Here is a reproducible example:
```bash
$ docker run --rm -it centos:7 bash
# yum install -y epel-release coreutils bash bzip2 java-1.8.0-openjdk
# curl https://repo.anaconda.com/miniconda/Miniconda3-4.5.4-Linux-x86_64.sh -o /tmp/Miniconda3-py36.sh \
    && bash /tmp/Miniconda3-py36.sh -b -f -p /opt/python36 \
    && rm -f /tmp/Miniconda3-py36.sh \
    && /opt/python36/bin/pip install -U pip wheel setuptools
# /opt/python36/bin/python -m venv venv
# venv/bin/pip install pandas pyspark findspark
```

When I now try running pyspark commands needing a python worker (without findspark):
```python
# venv/bin/python
>>> import pyspark
>>> spark = pyspark.sql.SparkSession.builder.getOrCreate()
>>> spark.createDataFrame([ [1] ], ['a']).show()
java.io.IOException: Cannot run program "python3": error=2, No such file or directory
...
```

If I do `spark.sql('SELECT 1').show()` - it works, because that doesn't need to spawn a container with a python worker. It only needs that for Python UDFs or for converting a python list to a DF, etc.

**Comment by minrk** [comment]
Gotcha, I had it backwards - the issue is that pyspark doesn't use sys.executable by default for PYPSPARK_PYTHON.

Does `os.environ["PYSPARK_PYTHON"] = sys.executable` make everything work?

**Comment by minrk** [comment]
Can you test #35?
