### ISSUE TITLE
incorrect SPARK_HOME in 2.0

### ISSUE THREAD

**Issue by rajeshd-coditation** [minrk/findspark#38]
Version 2.0.0 fires command spark-shell in wrong directory. It tries with
'/usr/lib/spark/python/pyspark/./bin/spark-submit' i.e SPARK_HOME, ./bin/spark-submit

when we rolled back to version 1.4.2 it worked without any issues.

**Comment by minrk** [comment]
Can you provide more context? Please share your $SPARK_HOME, where your spark installation is, and any calls to findspark functions. Have you pip-installed pyspark? Is pyspark already imported when you call `findspark.init()`?

**Comment by minrk** [comment]
I suspect this is fixed by #39

**Comment by minrk** [comment]
Can you test with findspark 2.0.1?

**Comment by ionicsolutions** [comment]
We had a similar issue and it was indeed resolved with 2.0.1

**Comment by minrk** [comment]
Thanks @ionicsolutions!
