### ISSUE TITLE
Does it work with Python 3.4?

### ISSUE THREAD

**Issue by stared** [minrk/findspark#6]
Spark 1.4.0 and above support Python 3.4. However, when I am trying to run Spark using 

```
import findspark
findspark.init()

import pyspark
sc = pyspark.SparkContext(appName="myAppName")

rdd = sc.parallelize([1,2,3])
rdd.count()
```

Then I am getting an error:

 "Exception: Python in worker has different version 2.7 than that in driver 3.4, PySpark cannot run with different minor versions".

Is it tested on Python 3.4?

**Comment by stared** [comment]
Apparently is does not:

I can lunch Spark (1.4.1) with Python 3.4 using

    $ PYSPARK_PYTHON=python3 PYSPARK_DRIVER_PYTHON=ipython PYSPARK_DRIVER_PYTHON_OPTS="notebook" ./bin/pyspark

but when I lunch it with `findspark`, no matter if I open Python 2 or Python 3 notebook, Spark workers get Python 2.7 (perhaps because my default `python` links to Python 2.7).

**Comment by stared** [comment]
import os
    os.environ["PYSPARK_PYTHON"] = "python3"

solves it on my computer. Yet, I don't know how to get path to Python, so that it would work regardless how it is being run (i.e. `python`, `ipython`, `ipython notebook`).

And ideas?

**Comment by Carreau** [comment]
hum... `import sys; sys.executable` could do the trick I think.

**Comment by stared** [comment]
@Carreau Thanks!

**Comment by minrk** [comment]
closed by #7

**Comment by suyogk** [comment]
I am facing the same problem with driver at 3.5.1 & workers at 2.7. I must admit, I do not understand your solution. where should I make these changes ?

**Comment by binxuan** [comment]
edit the file of ~/.ipython/profile_pyspark/startup/00-pyspark-setup.py
add a line: os.environ["PYSPARK_PYTHON"] = "python3"
